### PR TITLE
Do not use "gtk3" key to avoid conflict with QGtkStyle from Qt upstream

### PR DESCRIPTION
**Pull request by grulja**

### CODE REVIEW

**Comment by pacho2** [comment]
This change breaks the theming with all the QT apps I have tried to run on Gnome :/ (lyx, vlc and makemkv for now)

Is that intended? How are we supposed to get the "good looking" theming? I have seen you deprecated the project, but I am not sure about what to use instead :/

Thanks a lot

**Comment by grulja** [comment]
This change was intended to avoid using QGnomePlatform by default over QGtkStyle from Qt. Both use "gtk3" as a key to load the plugin, but we were picked first automatically thanks to alphabetical order. You can still use QGnomePlatform if you want to by just setting `QT_QPA_PLATFORMTHEME=qgnomeplatform` env variable.

**Comment by pacho2** [comment]
I thought QGtkStyle was dead long time ago... and the code that I have found was last touched in 2017:
https://code.qt.io/cgit/qt/qtstyleplugins.git/log/

Is there anything newer? If not... why prefer to go back to the old gtk2 theme over this? Even if both are deprecated... this looks at least more "updated" than the former

I guess in downstream packaging we can now install a env.d file to set the variable to mimic the old behavior (as people installing qgnomeplatform will expect it to get used without more manual intervention for every user)

**Comment by grulja** [comment]
> I thought QGtkStyle was dead long time ago... and the code that I have found was last touched in 2017: https://code.qt.io/cgit/qt/qtstyleplugins.git/log/
> 
Sorry, I meant QGtk3Theme. Looks I've been using the name wrongly all over the places.

This one: https://github.com/qt/qtbase/tree/dev/src/plugins/platformthemes/gtk3

**Comment by pacho2** [comment]
I have it installed for qt5 but, for some reason, it doesn't seem to be used automatically :/

I need to launch all the apps using QT_STYLE_OVERRIDE=adwaita (and with adwaita-qt installed) to get the right theming on GNOME

**Comment by pacho2** [comment]
Hello,

I have tried to suggest people to use the env variable but, then, that looks to collide with people using KDE. Is there a way to get the variable set only on GNOME setups?

Thanks

**Comment by grulja** [comment]
> Hello,
> 
> I have tried to suggest people to use the env variable but, then, that looks to collide with people using KDE. Is there a way to get the variable set only on GNOME setups?
> 
> Thanks

You can check whether `$XDG_CURRENT_DESKTOP == "GNOME"` and only in such case set the env variable to QGnomePlatform.

**Comment by pacho2** [comment]
I will see where to export it globally then, it seems under xinitrc.d stuff we have similar scripts for conditionally changing things.

Thanks a lot !

**Comment by pacho2** [comment]
Hello,

Sorry to bother you again with this, but even after searching a lot, I could not find a solution allowing me to completely drop QGnomePlatform usage.

What I am trying to achieve is that, at least on systems having Breeze qt6 theme, that theme is used preferentially over Fusion (as Fusion still looks a bit "old" on my system). 

Thanks to this recent change:
https://invent.kde.org/graphics/okular/-/commit/a1c2b9d14cf674a73197f11b6e285818dbd627f9

Okular looks to work without doing anything else, even if, still, QT_QPA_PLATFORMTHEME=qgnomeplatform allows it to use more "adwaita" style color patterns and also allows it to properly use gnome portals file pickers instead of old gtk3 ones.

The problem is for more pure QT apps (like LyX, celestia, virtualbox, qbittorrent). For those apps I am currently needing to pass QT_STYLE_OVERRIDE=Breeze. Isn't there a way at qt6 configuration level to firstly try Breeze and, if not available, fall back to Fusion? That would be really nice, as all apps would use a nicer theme as soon as it is present in the system without doing anything else.

Another issue is that, if I don't use qgnomeplatform, those Qt apps won't follow the light/dark mode switch and will also use the old gtk3 file pickers.

Thanks a lot for your help :)

**Comment by grulja** [comment]
Hello,

> The problem is for more pure QT apps (like LyX, celestia, virtualbox, qbittorrent). For those apps I am currently needing to pass QT_STYLE_OVERRIDE=Breeze. Isn't there a way at qt6 configuration level to firstly try Breeze and, if not available, fall back to Fusion? That would be really nice, as all apps would use a nicer theme as soon as it is present in the system without doing anything else.

I'm not aware of any solution to this problem. Possibly you can write a script that will set the env variable based on the installed styles? 

> Another issue is that, if I don't use qgnomeplatform, those Qt apps won't follow the light/dark mode switch and will also use the old gtk3 file pickers.

In Qt this should work through xdg-desktop-portal (settings portal), however, there was an issue and it didn't work reliably. I saw there is a fix for this upstream, but it will most likely be part of Qt 6.10.

**Pull request merged**
